// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgQV2S7aiTTunbERVTVqsUdPHGZgCkjOk',
    appId: '1:7565348775:web:fcc4630a4682f37e78f082',
    messagingSenderId: '7565348775',
    projectId: 'zarity-c8354',
    authDomain: 'zarity-c8354.firebaseapp.com',
    storageBucket: 'zarity-c8354.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5j2aNenS6b2_ikJCjCIZTCuWtCh68QL4',
    appId: '1:7565348775:android:0852f7114af7cab578f082',
    messagingSenderId: '7565348775',
    projectId: 'zarity-c8354',
    storageBucket: 'zarity-c8354.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzG5eEuabm9NMRPlw2eSaWhjaqaMDd3o0',
    appId: '1:7565348775:ios:b72dc6c87f27d42b78f082',
    messagingSenderId: '7565348775',
    projectId: 'zarity-c8354',
    storageBucket: 'zarity-c8354.firebasestorage.app',
    iosBundleId: 'com.example.zarity',
  );
}
